logging:
  level:
    root: WARN
    tacos: DEBUG
  file:
    name: log/tacocloud.log

taco:
  orders:
    pageSize: 10


  discount:
    codes:
      abcdef: 10
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---
spring:
  config:
    activate:
      on-profile: H2

  datasource:
    generate-unique-name: false
    name: tacocloud

---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/taco
    username: user
    password: password
    hikari:
      data: data.sql
  jpa:
    hibernate:
      ddl-auto: update